name: hypercp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pyqt=5.15
  - requests=2.28
  - tqdm=4.65
  - numpy=1.23
  - h5py=3.7
  - pytz=2022.7
  - matplotlib
  - scipy=1.10
  - pandas=1.5
  - pysolar=0.10
  - xarray=0.19
  - cdsapi=0.6
  - netcdf4=1.6
  - pytables=3.7
  - pyspectral=0.12
  - pyqtgraph
  - pip
  - pip:
    - py6s
    - punpy
    - fpdf2
