name: ocdb

channels:
  - conda-forge

dependencies:
  #
  # production dependencies
  #
  - click
  - pyyaml
  - pandas
  - openssl

  #
  # development dependencies
  #
  - httpretty
  - pytest
  - pytest-cov
  - flake8
  - ipython
