name: Build & Release Pipeline

on:
  push:
    branches:
      - master
      - bundle
#    tags:
#      - 'v[0-9]+.[0-9]+.*'
  workflow_dispatch:

jobs:

  Build:
    name: ğŸ“¦ Bundle Application
    uses: ./.github/workflows/Build.yml

  Release:
    name: ğŸ“ Draft Release Page
    uses: ./.github/workflows/Release.yml
    needs:
      - Build

  ArtifactCleanUp:
    name: ğŸ—‘ï¸ Artifact Cleanup
    runs-on: ubuntu-latest
    needs:
      - Build
      - Release
    steps:
      - name: Delete Artifact
        if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags')
        uses: geekyeggo/delete-artifact@v4
        with:
          name: ${{ needs.Build.outputs.files }}
          token: ${{ secrets.GITHUB_TOKEN }}
