name: Pipeline

on:
  push:
    branches:
      - master
      - bundle
  workflow_dispatch:

jobs:

  Build:
    name: ğŸ“¦ Bundle Application
    uses: ./.github/workflows/Build.yml

  Release:
    name: ğŸ“ Draft Release Page
    uses: ./.github/workflows/Release.yml
    needs:
      - Build

  ArtifactCleanUp:
    name: ğŸ—‘ï¸ Artifact Cleanup
    if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags')
    uses: geekyeggo/delete-artifact@v4
    needs:
      - Bundle
      - Release
    with:
      name: ${{ needs.Build.outputs.files }}
      token: ${{ secrets.GITHUB_TOKEN }}
