name: SetupEnvironment
description: 'Setup python environment with conda'

runs:
  using: "composite"
  steps:
    - name: ‚è¨ Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: üêç Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: hypercp
        use-mamba: true

    - name: Cache Environment
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      id: cache

    - name: Update Environment
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mamba env update -n hypercp -f environment.yml
        mamba install --channel=conda-forge pyinstaller==6.6

    - name: üìì Capture Environment
      run: |
        mamba info
        mamba list
